services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - './server:/config'
      - './certbot/letsencrypt/live/jjgrootjans.com/privkey.pem:/config/gamefiles/FactoryGame/Certificates/private_key.pem'
      - './certbot/letsencrypt/live/jjgrootjans.com/fullchain.pem:/config/gamefiles/FactoryGame/Certificates/cert_chain.pem'
      # fixing the timezone
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
      - SERVERIP=127.0.0.1
      - SERVERGAMEPORT=7777
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "bash", "/healthcheck.sh" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    networks:
      - satisfactory-cluster



  # node:
  #   container_name: node.js
  #   build: ./node
  #   image: node:23.1.0
  #   ports:
  #   - 3000:3000
  #   volumes:
  #     - .node:/usr/src/app
  #   environment:
  #   - PORT=3000
  #   networks:
  #     - satisfactory-cluster



  nginx:
    image: nginx:1.27.2
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/site:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx/
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./nginx/config/conf.d:/etc/nginx/conf.d
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      # fixing the timezone
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    networks:
      - satisfactory-cluster



  certbot:
    image: certbot/dns-cloudflare:latest
    container_name: certbot
    env_file:
      - ./certbot/secrets/.env
    depends_on:
      - nginx
    volumes:
      - ./certbot/secrets/cloudflare.ini:/cloudflare.ini:ro
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./certbot/log/letsencrypt:/var/log/letsencrypt
      - ./certbot/entrypoint.sh:/entrypoint.sh
      # fixing the timezone
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    entrypoint: "/bin/sh /entrypoint.sh"
    networks:
      - satisfactory-cluster

networks:
  satisfactory-cluster:
    driver: bridge
